# Generated by Django 3.2.6 on 2021-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.TextField(default='test supplier', max_length=255),
        ),
    ]
