# Generated by Django 3.2.6 on 2021-09-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitPrice',
            field=models.FloatField(default=1000),
        ),
    ]
