# Generated by Django 3.2.6 on 2021-09-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0006_auto_20210918_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
