# Generated by Django 3.2.6 on 2021-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_api', '0002_auto_20210829_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(default='none', max_length=255),
        ),
    ]
