# Generated by Django 3.2.6 on 2021-09-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_api', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='test description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(default='test', max_length=255),
        ),
    ]
