# Generated by Django 3.2.6 on 2021-09-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0003_auto_20210912_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='subTotal',
            new_name='subtotal',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='carts_api.cart'),
        ),
    ]
